### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Logan1x**

### CODE REVIEW

**Comment by Logan1x** [comment]
#1 added readme but stiil need to add content.

**Comment by Soumya44** [comment]
Please create  a proper readme

**Comment by rahuldcoder** [comment]
What content is required in README like the rules of contribution etc.??

**Comment by ZechariahRaman** [comment]
The README file should have a description of what the project is about. It can also describe the purpose of the project.

**Review by ZechariahRaman — APPROVED** [review]
I think this would be enough for now, isn't it? We'll add more details as we finish the project.

**Comment by Logan1x** [comment]
@Soumya44 

> Please create a proper readme
i know we need to add proper readme but the repo was looking ugly and i was busy so i added a readme file with repo name so one can edit and push a PR

**Comment by Soumya44** [comment]
I'll Create a Proper One. Thanks

**Pull request closed without merging**
